package ja.burhanrashid52.photoeditor;

public enum PhotoFilter {
    NINGUNO,
    AUTO_AJUSTAR,
    BLANCO_Y_NEGRO,
    BRILLO,
    CONTRASTE,
    PROCESO_CRUZADO,
    DOCUMENTAL,
    DOBLE_TONO,
    LUZ_DE_RELLENO,
    OJO_DE_PEZ,
    GIRAR_VERTICAL,
    GIRAR_HORIZONTAL,
    GRANO,
    GRIS,
    LOMISH,
    NEGATIVO,
    POSTERIZAR,
    ROTAR,
    SATURADO,
    SEPIA,
    AFILAR,
    TEMPERATURA,
    TINTE,
    VIÑETA,

//    NONE,
//    AUTO_FIX,
//    BLACK_WHITE,
//    BRIGHTNESS,
//    CONTRAST,
//    CROSS_PROCESS,
//    DOCUMENTARY,
//    DUE_TONE,
//    FILL_LIGHT,
//    FISH_EYE,
//    FLIP_VERTICAL,
//    FLIP_HORIZONTAL,
//    GRAIN,
//    GRAY_SCALE,
//    LOMISH,
//    NEGATIVE,
//    POSTERIZE,
//    ROTATE,
//    SATURATE,
//    SEPIA,
//    SHARPEN,
//    TEMPERATURE,
//    TINT,
//    VIGNETTE,
}
